import streamlit as st
import google.generativeai as genai
import fitz  # PyMuPDF
from PIL import Image
import io
import markdown
from weasyprint import HTML
import os

# --- CONFIG ---
st.set_page_config(page_title="Ashraf AI Note Architect", page_icon="📚")

# --- API KEY SETUP (SECRETS METHOD) ---
if "GOOGLE_API_KEY" in st.secrets:
    api_key = st.secrets["GOOGLE_API_KEY"]
else:
    api_key = os.getenv("GOOGLE_API_KEY")

if api_key:
    genai.configure(api_key=api_key)
    model = genai.GenerativeModel('gemini-3-flash')
else:
    st.error("⚠️ Developer Note: API Key missing in Streamlit Secrets!")

# --- STYLING ---
st.markdown("""
    <style>
    .stButton>button { width: 100%; background-color: #6C63FF; color: white; border-radius: 10px; height: 3em; font-weight: bold; }
    </style>
    """, unsafe_allow_html=True)

st.title("📄 AI Textbook Architect")
st.markdown("Created by **Syed Tameem Ashraf**")

# --- SIDEBAR ---
with st.sidebar:
    st.header("Settings")
    note_depth = st.select_slider("Detail Level", options=["Summary", "Detailed", "Mastery"])
    st.divider()
    st.info("Upload your textbook images or PDFs, and I will generate professional study notes for you.")

# --- PDF EXPORT FUNCTION ---
def export_as_pdf(text_content):
    html_body = markdown.markdown(text_content)
    full_html = f"""
    <html>
    <head><style>body {{ font-family: sans-serif; padding: 40px; line-height: 1.6; }} h1 {{ color: #2E3192; }}</style></head>
    <body>
        <h1>Study Notes</h1>
        <p>Generated by Ashraf AI Architect</p>
        <hr>{html_body}
    </body>
    </html>
    """
    return HTML(string=full_html).write_pdf()

# --- MAIN APP LOGIC ---
uploaded_files = st.file_uploader("Upload Textbook Pages", type=["pdf", "png", "jpg"], accept_multiple_files=True)

if uploaded_files:
    if st.button("🪄 Generate Professional PDF"):
        with st.spinner("Analyzing pages and writing notes..."):
            content_to_send = [f"Create structured {note_depth} Grade 11 academic notes based on these images. Use clear headings and bullet points."]
            
            for f in uploaded_files:
                if f.type == "application/pdf":
                    doc = fitz.open(stream=f.read(), filetype="pdf")
                    for p in doc:
                        pix = p.get_pixmap()
                        img = Image.open(io.BytesIO(pix.tobytes()))
                        content_to_send.append(img)
                else:
                    # This ensures the image is correctly formatted for Gemini
                    img = Image.open(f)
                    content_to_send.append(img)

            try:
                # Send everything to the model
                response = model.generate_content(content_to_send)
                
                # Show preview
                st.markdown("### Preview:")
                st.markdown(response.text)
                
                # PDF Download
                pdf_data = export_as_pdf(response.text)
                st.download_button(
                    label="📥 Download Study Guide (PDF)",
                    data=pdf_data,
                    file_name="Study_Notes_Ashraf_AI.pdf",
                    mime="application/pdf"
                )
            except Exception as e:
                st.error(f"AI Error: {e}")
                st.info("Try uploading fewer pages or using JPG/PNG images instead of PDF.")
            
            # Show preview
            st.markdown("### Preview:")
            st.markdown(response.text)
            
            # PDF Download
            pdf_data = export_as_pdf(response.text)
            st.download_button(
                label="📥 Download Study Guide (PDF)",
                data=pdf_data,
                file_name="Study_Notes_Ashraf_AI.pdf",
                mime="application/pdf"
            )
